language: c

git:
  depth: 1500

compiler:
  - gcc
  - clang

env:
  global:
  # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
  # via the "travis encrypt" command using the project repo's public key
  - secure: "X5xVT8S0hsnT5cyDzmQbKr68kunpI1VyNADD/bMcEjPiBO2p6/iWHSfAqRP3q2UEqt92XgwCd8cuSVffdagbin4JlvA5fgnCWkcCphC8k79jhHqz9aoK97qbSXBHLU4yDimeC/m9HlslBc/zjPAc+s9/7UKBXQI+YN9ITL1i7pQ="
  - MAKE_CHECK="nonroot"
  - MAKE_CHECK="root"
  - MAKE_CHECK="dist"

branches:
  only:
    - master
    - /^stable.*/
    - /^travis.*/

install:
  - source ./.travis-functions.sh
  - travis_install_script

before_script:
  - travis_before_script

script:
  - travis_script

after_script:
  - travis_after_script

before_install:
  - $CC --version
  - which $CC
  # workaround clang not system wide, fail on sudo make install
  - export CC=`which $CC`

addons:
  coverity_scan:
    project:
      name: "karelzak/util-linux"
      description: "Build submitted via Travis CI"
      notification_email: kzak@redhat.com
      build_command_prepend: travis_before_script
      build_command: "make"
      branch_pattern: coverity_scan
